### ISSUE TITLE
Configurar cuenta de usuario

### ISSUE THREAD

**Issue by amateusr** [amateusr/github_install#5]
git config --global user.name "testuser"
git config --global user.email "testuser@example.com"

user.name es el username de github
testuse@example es el correo registrado en github

**Comment by Paolamaya** [comment]
En la aclaración: testuser es el username de github. Las líneas de comando que ejecuté son las siguientes:
git config --global user.name "Paolamaya"
git config --global user.email "amayasindypaola@gmail.com"
